apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/torestokkedal/Data/K8Volumes"