apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  volumes:
    - name: mariadb-pv
      persistentVolumeClaim:
        claimName: mariadb-pv-claim
  containers:
    - name: mariadb
      image: mariadb:latest
      ports:
        - name: mariadb
          protocol: TCP
          containerPort: 3306
      env:
      # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        value: password
      volumeMounts:
        - mountPath: "/var/lib/mariadb"
          name: mariadb-pv